version: '3.9'
services:
  ssh.cyrhades.com:
    build: ssh
  webssh.cyrhades.com:
    build: webssh
    ports:
      - "80:8888"
  pippin.cyrhades.com:
    image: anssi/fcsc2020-crypto-pippin:latest
    ports:
      - "4000:4000"